export const portfolio = [
  {
    title: "Cursos",
    id: "cursos",
    //icon: Home,
  },

  {
    title: "Eventos",
    id: "eventos",
    //icon: Home,
  },
  {
    title: "Ensaios",
    id: "ensaios",
    //icon: Home,
  },
  {
    title: "Gastronômico",
    id: "gastronomia",
    //icon: Home,
  },
  {
    title: "Influencers",
    id: "influencers",
    //icon: Home,
  },
  {
    title: "Institucional",
    id: "institucional",
    //icon: Home,
  },
  {
    title: "Marketing pessoal e profissional",
    id: "marketing",
    //icon: Home,
  },
  {
    title: "Produtos",
    id: "produtos",
    //icon: Home,
  },
];

export const projects = {
  cursos: [
    {
      id: "nutrir",
      cover: "/projects/cursos-ads/nutrir/14 - capa.png",
      title: "Amor em Nutrir",
      description: "video aula amor em nutrir",
      videos: ["/projects/cursos-ads/nutrir/video/14 - video.mp4"],
      images: [],
    },
    {
      id: "ana",
      cover: "/projects/cursos-ads/ana/15 - capa.png",
      title: "Ana Costa Consorcios",
      description: "Chamada para atendimento",
      videos: ["/projects/cursos-ads/ana/video/15 - video.mp4"],
      images: [],
    },
  ],
  marketing: [
    {
      id: "ana2025",
      cover: "/projects/marketing/ana2025/16 - capa.png",
      title: "Ana Costa Consorcios",
      description: "churrascaria dona nicemetas 2025",
      videos: ["/projects/marketing/ana2025/video/16 - video.mp4"],
      images: [],
    },
    {
      id: "miriam",
      cover: "/projects/marketing/miriam/17 - capa.png",
      title: "Miriam Bernardes",
      description: "black friday",
      videos: ["/projects/marketing/miriam/video/17 - video.mp4"],
      images: [],
    },
    {
      id: "sandro",
      cover: "/projects/marketing/sandro/18 - capa.png",
      title: "Sandro Costa",
      description: "dica de consorcio",
      videos: ["/projects/marketing/sandro/video/18 - video.mp4"],
      images: [],
    },
    {
      id: "capilar",
      cover: "/projects/marketing/capilar/21 - capa.png",
      title: "Clinica Sirus",
      description: "implante capilar",
      videos: ["/projects/marketing/capilar/video/21 - video.mp4"],
      images: [],
    },
    {
      id: "300k",
      cover: "/projects/marketing/300k/46 - capa.png",
      title: "sandro costa",
      description: "dica de investimento com consorcio",
      videos: ["/projects/marketing/300k/video/46 - video.mp4"],
      images: [],
    },
    {
      id: "tempo",
      cover: "/projects/marketing/tempo/52 - capa.png",
      title: "tempo",
      description: "analise de tempo para Janaina Hohne",
      videos: ["/projects/marketing/tempo/videos/52 - video.mp4"],
      images: [],
    },
    {
      id: "verao",
      cover: "/projects/marketing/verao/51 - capa.png",
      title: "verao nova emergencias",
      description: "publicidade para Janaina Hohne",
      videos: ["/projects/marketing/verao/video/51 - video.mp4"],
      images: [],
    },
    {
      id: "costura",
      cover: "/projects/marketing/costura/24 - capa.png",
      title: "Alvares Uniformes",
      description: "confecção de uniformes",
      videos: ["/projects/marketing/costura/video/24 - video.mp4"],
      images: [],
    },
    {
      id: "edit",
      cover: "/projects/marketing/edit/56 - capa.png",
      title: "Fotografia Leandro",
      description: "antes e depois de edições",
      videos: ["/projects/marketing/edit/video/56 - video.mp4"],
      images: [],
    },
    {
      id: "cancer1",
      cover: "/projects/marketing/cancer1/25 - capa.png",
      title: "clinica sirus",
      description: "outubro rosa",
      videos: ["/projects/marketing/cancer1/video/25 - video.mp4"],
      images: [],
    },
    {
      id: "cancer2",
      cover: "/projects/marketing/cancer2/26 - capa.png",
      title: "clinica sirus",
      description: "outubro rosa",
      videos: ["/projects/marketing/cancer2/video/26 - video.mp4"],
      images: [],
    },
    {
      id: "reforma",
      cover: "/projects/marketing/reforma/22 - capa.png",
      title: "vlog de reforma",
      description: "vlog de reforma do apartamento",
      videos: ["/projects/marketing/reforma/video/22 - video.mp4"],
      images: [],
    },
    {
      id: "bni",
      cover: "/projects/marketing/bni/23 - capa.png",
      title: "bni",
      description: "resumo do evento bni",
      videos: ["/projects/marketing/bni/video/23 - video.mp4"],
      images: [],
    },
    {
      id: "gcm",
      cover: "/projects/marketing/gcm/30 - capa.png",
      title: "gcm",
      description: "palesta ana e sandro",
      videos: ["/projects/marketing/gcm/video/30 - video.mp4"],
      images: [],
    },
    {
      id: "vanessa",
      cover: "/projects/marketing/vanessa/36 - capa.png",
      title: "vanessa brito comestics",
      description: "apresentação de produtos vanessa brito",
      videos: ["/projects/marketing/vanessa/video/36 - video.mp4"],
      images: [],
    },
    {
      id: "varizes",
      cover: "/projects/marketing/varizes/32 - capa.png",
      title: "varizes",
      description: "dr alisson zamara",
      videos: ["/projects/marketing/varizes/video/32 - video.mp4"],
      images: [],
    },
    {
      id: "foto",
      cover: "/projects/marketing/foto/54 - capa.png",
      title: "Fotografia Leandro",
      description: "resultados dos ensaios",
      videos: ["/projects/marketing/fotos/video/54 - video.mp4"],
      images: [],
    },
    4,
  ],
  produtos: [
    {
      id: "cis",
      cover: "/projects/produtos/cis/20 - capa.png",
      title: "Canetas Cis",
      description: "apresentação de canetas cis",
      videos: ["/projects/produtos/fotos/video/20 - video.mp4"],
      images: [],
    },
    {
      id: "hp",
      cover: "/projects/produtos/hp/59 - capa.png",
      title: "Caneca Harry Potter",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/hp/video/59 - video.mp4"],
      images: [],
    },
    {
      id: "copo",
      cover: "/projects/produtos/copo/39 - capa.png",
      title: "Copo Whiskey",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/copo/video/39 - video.mp4"],
      images: [],
    },
    {
      id: "panela",
      cover: "/projects/produtos/panela/57 - capa.png",
      title: "Panelas",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/panela/video/57 - video.mp4"],
      images: [],
    },
    {
      id: "pratos",
      cover: "/projects/produtos/pratos/60 - capa.png",
      title: "mesa posta",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/pratos/video/60 - video.mp4"],
      images: [],
    },
    {
      id: "lego",
      cover: "/projects/produtos/lego/62 - capa.png",
      title: "brinquedo de montar",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/lego/video/62 - video.mp4"],
      images: [],
    },
    {
      id: "pote",
      cover: "/projects/produtos/pote/61 - capa.png",
      title: "potinho",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/pote/video/61 - video.mp4"],
      images: [],
    },
    {
      id: "taca",
      cover: "/projects/produtos/taca/40 - capa.png",
      title: "taca de sobremesa",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/taca/video/40 - video.mp4"],
      images: [],
    },
    {
      id: "mel",
      cover: "/projects/produtos/mel/58 - capa.png",
      title: "Meleira",
      description: "publicidade para agencia",
      videos: ["/projects/produtos/mel/video/58 - video.mp4"],
      images: [],
    },
  ],
  institucional: [
    {
      id: "FMU",
      cover: "/projects/institucional/FMU/capa.png",
      title: "Faculdade FMU",
      description:
        "Projeto feito para a Faculdade FMU, durante meu tempo de trabalho na ME digital.",
      videos: ["/projects/institucional/FMU/videos/video1.mp4"],
      images: [],
    },

    {
      id: "retro-me",
      cover: "/projects/institucional/retro-me/27 - capa.png",
      title: "Retrospectiva Me digital",
      description: " trend para a empresa me digital",
      videos: ["/projects/institucional/retro-me/video/27 - video.mp4"],
      images: [],
    },
    {
      id: "trend-me",
      cover: "/projects/institucional/trend-me/1 - capa.png",
      title: "Trend Me digital",
      description: " trend para a empresa me digital",
      videos: ["/projects/institucional/trend-me/video/1 - video.mp4"],
      images: [],
    },
    {
      id: "comfort",
      cover: "/projects/institucional/comfort/34 - capa.png",
      title: "apresentação Comfort",
      description: "apresentação Comfort",
      videos: ["/projects/institucional/comfort/video/34 - video.mp4"],
      images: [],
    },
    {
      id: "pascoa-akai",
      cover: "/projects/institucional/pascoa-akai/11 - capa.png",
      title: "pascoa akai",
      description: "pascoa akai comesmeticos",
      videos: ["/projects/institucional/pascoa-akai/video/11 - video.mp4"],
      images: [],
    },
    {
      id: "krill",
      cover: "/projects/institucional/krill/48 - foto.png",
      title: "krill",
      description: "krill cozinha",
      videos: ["/projects/institucional/krill/video/48 - video.mp4"],
      images: [],
    },
    {
      id: "mulher-me",
      cover: "/projects/institucional/mulher-me/33- capa.png",
      title: "dia da mulher me digital",
      description: "dia da mulher me digital",
      videos: ["/projects/institucional/krill/video/33 - video.mp4"],
      images: [],
    },
  ],
  influencers: [],
  gastronomia: [
    {
      id: "donanice1",
      cover: "/projects/gastronomico/donanice1/50 - capa.png",
      title: "DJ TSHOW",
      description: "churrascaria dona nice",
      videos: ["/projects/gastronomico/donanice1/video/50 - video.mp4"],
      images: [],
    },
    {
      id: "manteigaria1",
      cover: "/projects/gastronomico/manteigaria1/49 - capa.png",
      title: "manteigaria do porto",
      description: "manteigaria do porto",
      videos: ["/projects/gastronomico/manteigaria1/video/49 - video.mp4"],
      images: [],
    },
    {
      id: "moqueca",
      cover: "/projects/gastronomico/moqueca/45 - capa.png",
      title: "moqueca",
      description: "moqueca pedra baiana",
      videos: ["/projects/gastronomico/moqueca/video/45 - video.mp4"],
      images: [],
    },
    {
      id: "donanice2",
      cover: "/projects/gastronomico/donanice2/47 - capa.png",
      title: "dona nice",
      description: "carnes dona nice",
      videos: ["/projects/gastronomico/donanice2/video/47 - video.mp4"],
      images: [],
    },
    {
      id: "bemservido",
      cover: "/projects/gastronomico/bemservido/44 - capa.png",
      title: "pedra baiana ",
      description: "seja bem servido",
      videos: ["/projects/gastronomico/bemservido/video/44 - video.mp4"],
      images: [],
    },
    {
      id: "carnedesol",
      cover: "/projects/gastronomico/carnedesol/43 - capa.png",
      title: "pedra baiana ",
      description: "carne de sol",
      videos: ["/projects/gastronomico/carnedesol/video/43 - video.mp4"],
      images: [],
    },
    {
      id: "provolone",
      cover: "/projects/gastronomico/provolone/42 - capa.png",
      title: "pedra baiana ",
      description: "provolone a milanesa",
      videos: ["/projects/gastronomico/carnedesol/video/42 - video.mp4"],
      images: [],
    },
    {
      id: "strogonof",
      cover: "/projects/gastronomico/strogonof/38 - capa.png",
      title: "pedra baiana ",
      description: "strogonof",
      videos: ["/projects/gastronomico/strogonof/video/38 - video.mp4"],
      images: [],
    },
    {
      id: "sextasanta",
      cover: "/projects/gastronomico/sextasanta/41- capa.png",
      title: "pedra baiana ",
      description: "sexta feira santa",
      videos: ["/projects/gastronomico/sextasanta/video/41- video.mp4"],
      images: [],
    },
    {
      id: "mocoto",
      cover: "/projects/gastronomico/mocoto/37 - capa.png",
      title: "pedra baiana ",
      description: "mocoto",
      videos: ["/projects/gastronomico/mocoto/video/37 - video.mp4"],
      images: [],
    },
    {
      id: "piki",
      cover: "/projects/gastronomico/piki/29 - capa.png",
      title: "piki burguer",
      description: "retrospetiva piki",
      videos: ["/projects/gastronomico/piki/video/29 - video.mp4"],
      images: [],
    },
    {
      id: "petiscos",
      cover: "/projects/gastronomico/petiscos/8 - capa.png",
      title: "pedra baiana ",
      description: "bloquinho dos petiscos",
      videos: ["/projects/gastronomico/petiscos/video/8 - video.mp4"],
      images: [],
    },
    {
      id: "camarao",
      cover: "/projects/gastronomico/camarao/7 - capa.png",
      title: "pedra baiana ",
      description: "camarao recheado ",
      videos: ["/projects/gastronomico/camarao/video/7 - video.mp4"],
      images: [],
    },
    {
      id: "carnepais",
      cover: "/projects/gastronomico/carnepais/6 - capa.png",
      title: "receita para pais",
      description: "receita de carne para dia dos pais ",
      videos: ["/projects/gastronomico/carnepais/video/6 - video.mp4"],
      images: [],
    },
    {
      id: "escuta",
      cover: "/projects/gastronomico/escuta/5 - capa.png",
      title: "pedra baiana ",
      description: "escuta o cheiro - costela ",
      videos: ["/projects/gastronomico/escuta/video/5 - video.mp4"],
      images: [],
    },
    {
      id: "drink",
      cover: "/projects/gastronomico/drink/4 - capa.png",
      title: "pedra baiana ",
      description: "drinks para happy hour",
      videos: ["/projects/gastronomico/drink/video/4 - video.mp4"],
      images: [],
    },
    {
      id: "lanche",
      cover: "/projects/gastronomico/lanche/3 - capa.png",
      title: "pedra baiana ",
      description: "lanches da casa",
      videos: ["/projects/gastronomico/lanche/video/3 - video.mp4"],
      images: [],
    },
    {
      id: "salada",
      cover: "/projects/gastronomico/salada/2 - capa.png",
      title: "pedra baiana ",
      description: "saladas da casa",
      videos: ["/projects/gastronomico/salada/video/2 - video.mp4"],
      images: [],
    },
  ],
  ensaios: [
    {
      id: "make",
      cover: "/projects/make/1.JPG",
      title: "Make Ana Costa",
      description: "cobertura de backstage para ensaio da Ana Costa",
      videos: [],
      images: [
        "/projects/ensaios/make/2.JPG",
        "/projects/ensaios/make/3.JPG",
        "/projects/ensaios/make/4.JPG",
        "/projects/ensaios/make/5.JPG",
        "/projects/ensaios/make/6.JPG",
        "/projects/ensaios/make/7.JPG",
        "/projects/ensaios/make/8.JPG",
        "/projects/ensaios/make/9.JPG",
        "/projects/ensaios/make/10.JPG",
        "/projects/ensaios/make/11.JPG",
        "/projects/ensaios/make/12.JPG",
        "/projects/ensaios/make/13.JPG",
        "/projects/ensaios/make/14.JPG",
        "/projects/ensaios/make/15.JPG",
        "/projects/ensaios/make/16.JPG",
        "/projects/ensaios/make/17.JPG",
        "/projects/ensaios/make/18.JPG",
      ],
    },
    {
      id: "backstage",
      cover: "/projects/backstage/1.JPG",
      title: "Backstage Ana Costa",
      description: "cobertura de backstage para ensaio da Ana Costa",
      videos: [],
      images: [
        "/projects/ensaios/bakstage/2.JPG",
        "/projects/ensaios/backstage/3.JPG",
        "/projects/ensaios/backstage/4.JPG",
        "/projects/ensaios/backstage/5.JPG",
        "/projects/ensaios/backstage/6.JPG",
        "/projects/ensaios/backstage/7.JPG",
        "/projects/ensaios/backstage/8.JPG",
        "/projects/ensaios/backstage/9.JPG",
        "/projects/ensaios/backstage/10.JPG",
        "/projects/ensaios/backstage/11.JPG",
        "/projects/ensaios/backstage/12.JPG",
        "/projects/ensaios/backstage/13.JPG",
        "/projects/ensaios/backstage/14.JPG",
        "/projects/ensaios/backstage/15.JPG",
        "/projects/ensaios/backstage/16.JPG",
        "/projects/ensaios/backstage/17.JPG",
        "/projects/ensaios/backstage/18.JPG",
        "/projects/ensaios/backstage/19.JPG",
        "/projects/ensaios/backstage/20.JPG",
        "/projects/ensaios/backstage/21.JPG",
        "/projects/ensaios/backstage/22.JPG",
        "/projects/ensaios/backstage/23.JPG",
      ],
    },
    {
      id: "pod",
      cover: "/projects/pod/34.JPG",
      title: "Backstage de Podcast",
      description: "cobertura de backstage para podcast PodSimplificar",
      videos: [],
      images: [
        "/projects/ensaios/pod/2.JPG",
        "/projects/ensaios/pod/3.JPG",
        "/projects/ensaios/pod/4.JPG",
        "/projects/ensaios/pod/5.JPG",
        "/projects/ensaios/pod/6.JPG",
        "/projects/ensaios/pod/7.JPG",
        "/projects/ensaios/pod/8.JPG",
        "/projects/ensaios/pod/9.JPG",
        "/projects/ensaios/pod/10.JPG",
        "/projects/ensaios/pod/11.JPG",
        "/projects/ensaios/pod/12.JPG",
        "/projects/ensaios/pod/13.JPG",
        "/projects/ensaios/pod/14.JPG",
        "/projects/ensaios/pod/15.JPG",
        "/projects/ensaios/pod/16.JPG",
        "/projects/ensaios/pod/17.JPG",
        "/projects/ensaios/pod/18.JPG",
        "/projects/ensaios/pod/19.JPG",
        "/projects/ensaios/pod/20.JPG",
        "/projects/ensaios/pod/21.JPG",
        "/projects/ensaios/pod/22.JPG",
        "/projects/ensaios/pod/23.JPG",
        "/projects/ensaios/pod/24.JPG",
        "/projects/ensaios/pod/24.JPG",
        "/projects/ensaios/pod/25.JPG",
        "/projects/ensaios/pod/26.JPG",
        "/projects/ensaios/pod/27.JPG",
        "/projects/ensaios/pod/28.JPG",
        "/projects/ensaios/pod/29.JPG",
        "/projects/ensaios/pod/30.JPG",
        "/projects/ensaios/pod/32.JPG",
        "/projects/ensaios/pod/33.JPG",
        "/projects/ensaios/pod/1.JPG",
        ,
      ],
    },
    {
      id: "pirotecnia",
      cover: "/projects/pirotecnia/1.JPG",
      title: "Make Ana Costa",
      description: "cobertura de backstage para ensaio da Ana Costa",
      videos: [],
      images: [
        "/projects/ensaios/pirotecnia/2.JPG",
        "/projects/ensaios/pirotecnia/3.JPG",
        "/projects/ensaios/pirotecnia/4.JPG",
        "/projects/ensaios/pirotecnia/5.JPG",
        "/projects/ensaios/pirotecnia/6.JPG",
        "/projects/ensaios/pirotecnia/7.JPG",
        "/projects/ensaios/pirotecnia/8.JPG",
        "/projects/ensaios/pirotecnia/9.JPG",
        "/projects/ensaios/pirotecnia/10.JPG",
      ],
    },
  ],
  eventos: [
    {
      id: "DJ-TSHOW",
      cover: "/projects/eventos/DJ-TCHOW/10 - cap.png",
      title: "DJ TSHOW",
      description: "Evento do DJ TSHOW, realizado em São Paulo.",
      videos: ["/projects/eventos/DJ-TCHOW/videos/video.mp4"],
      images: [],
    },
    {
      id: "DJ-Festa-gaia",
      cover: "/projects/eventos/Festa-gaia/12 - capa.png",
      title: "festa gaia",
      description: "Evento do DJ TSHOW, realizado em São Paulo.",
      videos: ["/projects/eventos/festa-gaia/videos/12 - video.mp4"],
      images: [],
    },
    {
      id: "Circo-Abracadabra",
      cover: "/projects/eventos/Circo-Abracadabra/63 - capa.png",
      title: "Circo  Abracadabra",
      description: "apresentação do circo Abracadabra",
      videos: ["/projects/eventos/Circo-Abracadabra/video/63 - video.mp4"],
      images: [],
    },
    {
      id: "circo-abracadabra-geral",
      cover: "/projects/eventos/circo-abracadabra-geral/53 - capa.png",
      title: "Circo  Abracadabra",
      description: "apresentação do circo Abracadabra",
      videos: [
        "/projects/eventos/circo-abracadabra-geral/video/53 - video.mp4",
      ],
      images: [],
    },
    {
      id: "atol",
      cover: "/projects/eventos/atol/13 - capa.png",
      title: "Aniversario Atol",
      description: "evento de aniversario da Atol",
      videos: ["/projects/eventos/atol/video/13 - video.mp4"],
      images: [],
    },
    {
      id: "serena",
      cover: "/projects/eventos/serena/9 - capa.png",
      title: "palestra serena",
      description: "palestra serena",
      videos: ["/projects/eventos/serena/video/9 - video.mp4"],
      images: [],
    },
  ],
};
