export const portfolio = [
  {
    title: "Comerciais e publicidade",
    id: "cursos",
    //icon: Home,
  },

  {
    title: "Eventos",
    id: "eventos",
    //icon: Home,
  },
  {
    title: "Ensaios e fotografias",
    id: "ensaios",
    //icon: Home,
  },
  {
    title: "Gastronômico",
    id: "gastronomia",
    //icon: Home,
  },
  {
    title: "Influencers",
    id: "influencers",
    //icon: Home,
  },
  {
    title: "Institucional",
    id: "institucional",
    //icon: Home,
  },
  {
    title: "Marketing pessoal e profissional",
    id: "marketing",
    //icon: Home,
  },
  {
    title: "Produtos",
    id: "produtos",
    //icon: Home,
  },
];

export const projects = {
  cursos: [
    {
      id: "nutrir",
      cover: "/projects/cursos-ads/nutrir/14 - capa.png",
      title: "Amor em Nutrir",
      description: "Edição de video aula para Amor em Nutrir",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/cursos-ads/nutrir/video/14 - video.mp4",
      ],
      images: [],
    },
    {
      id: "ana",
      cover: "/projects/cursos-ads/ana/15 - capa.png",
      title: "Ana Costa Consórcios",
      description: "Chamada para atendimento via whatsapp",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/cursos-ads/ana/video/15 - video.mp4",
      ],
      images: [],
    },
    {
      id: "mtv",
      cover: "/projects/cursos-ads/mtv/capa/capas.png",
      title: "Documentário Descanse em Paz MTV",
      description: "documentario universitário em homenagem a antiga emissora",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/cursos-ads/mtv/1.mp4",
      ],
      images: [],
    },
  ],
  marketing: [
    {
      id: "ana2025",
      cover: "/projects/marketing/ana2025/16 - capa.png",
      title: "Ana Costa Consórcios",
      description: "Reels para anúncio e mkt da Ana Costa Consórcios",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/ana2025/video/16 - video.mp4",
      ],
      images: [],
    },
    {
      id: "miriam",
      cover: "/projects/marketing/miriam/17 - capa.png",
      title: "Miriam Bernardes",
      description: "Reels para anúncio e mkt da Miriam Bernardes",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/miriam/video/17 - video.mp4",
      ],
      images: [],
    },
    {
      id: "sandro",
      cover: "/projects/marketing/sandro/18 - capa.png",
      title: "Sandro Costa",
      description: "Reels para anúncio e mkt do Sandro Costa",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/sandro/video/18 - video.mp4",
      ],
      images: [],
    },
    {
      id: "capilar",
      cover: "/projects/marketing/capilar/21 - capa.png",
      title: "Clinica Sirus",
      description:
        "Reels para anúncio e mkt da Clinica Sirus, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/capilar/video/21 - video.mp4",
      ],
      images: [],
    },
    {
      id: "300k",
      cover: "/projects/marketing/300k/46 - capa.png",
      title: "Sandro Costa",
      description: "Reels para anúncio e mkt do Sandro Costa",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/300k/video/46 - video.mp4",
      ],
      images: [],
    },
    {
      id: "tempo",
      cover: "/projects/marketing/tempo/52 - capa.png",
      title: "Ánalise de tempo",
      description: "Ánalise de tempo para redes sociais da Janaina Hohne",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/tempo/videos/52 - video.mp4",
      ],
      images: [],
    },
    {
      id: "verao",
      cover: "/projects/marketing/verao/51 - capa.png",
      title: "verao nova emergencias",
      description: "publicidade para Janaina Hohne",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/verao/video/51 - video.mp4",
      ],
      images: [],
    },
    {
      id: "costura",
      cover: "/projects/marketing/costura/24 - capa.png",
      title: "Alvares Uniformes",
      description:
        "Reels para anúncio e mkt da Alvares Uniformes e Coratti em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/costura/video/24 - video.mp4",
      ],
      images: [],
    },
    {
      id: "edit",
      cover: "/projects/marketing/edit/56 - capa.png",
      title: "Fotografia Leandro",
      description: "Reels para anúncio e mkt do fotógrafo Leandro Cruz",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/edit/video/56 - video.mp4",
      ],
      images: [],
    },
    {
      id: "cancer1",
      cover: "/projects/marketing/cancer1/25 - capa.png",
      title: "Outubro rosa Clinica Sirus",
      description: "Reels de depoimento para Clinica Sirus",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/cancer1/video/25 - video.mp4",
      ],
      images: [],
    },
    {
      id: "cancer2",
      cover: "/projects/marketing/cancer2/26 - capa.png",
      title: "Outubro rosa Clinica Sirus",
      description: "Reels de depoimento para Clinica Sirus",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/cancer2/video/26 - video.mp4",
      ],
      images: [],
    },
    {
      id: "reforma",
      cover: "/projects/marketing/reforma/22 - capa.png",
      title: "Vlog de Reforma",
      description: "Vlog de reforma do apartamento da Ana e Sandro Costa",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/reforma/video/22 - video.mp4",
      ],
      images: [],
    },
    {
      id: "bni",
      cover: "/projects/marketing/bni/23 - capa.png",
      title: "BNI",
      description: "Aftermovie do evento BNI",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/bni/video/23 - video.mp4",
      ],
      images: [],
    },
    {
      id: "gcm",
      cover: "/projects/marketing/gcm/30 - capa.png",
      title: "Palestra GCM",
      description: "Aftermovie do evento GCM, com Ana e Sandro Costa",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/gcm/video/30 - video.mp4",
      ],
      images: [],
    },
    {
      id: "vanessa",
      cover: "/projects/marketing/vanessa/36 - capa.png",
      title: "Vanessa Brito Comestics",
      description: "Reels de publicidade para Vanessa Brito",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/vanessa/video/36 - video.mp4",
      ],
      images: [],
    },
    {
      id: "varizes",
      cover: "/projects/marketing/varizes/32 - capa.png",
      title: "Dr Alisson Zamara",
      description: "Reels de publicidade para Dr Alisson Zamara",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/varizes/video/32 - video.mp4",
      ],
      images: [],
    },
    {
      id: "foto",
      cover: "/projects/marketing/fotos/54 - capa.png",
      title: "Fotografia  Leandro Cruz",
      description: "Reels de publicidade para Leandro Cruz",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/marketing/fotos/video/54 - video.mp4",
      ],
      images: [],
    },
  ],
  produtos: [
    {
      id: "cis",
      cover: "/projects/produtos/cis/20 - capa.png",
      title: "Canetas Cis",
      description:
        "Reels de publicidade para canetas Cis, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/cis/video/20 - video.mp4",
      ],
      images: [],
    },
    {
      id: "hp",
      cover: "/projects/produtos/hp/59 - capa.png",
      title: "Caneca Harry Potter",
      description:
        "Reels de publicidade para caneca Harry Potter, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/hp/video/59 - video.mp4",
      ],
      images: [],
    },
    {
      id: "copo",
      cover: "/projects/produtos/copo/39 - capa.png",
      title: "Copo Whiskey",
      description:
        "Reels de publicidade para linha de copo whiskey, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/copo/video/39 - video.mp4",
      ],
      images: [],
    },
    {
      id: "panela",
      cover: "/projects/produtos/panela/57 - capa.png",
      title: "Panelas",
      description:
        "Reels de publicidade para linha de panelas, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/panela/video/57 - video.mp4",
      ],
      images: [],
    },
    {
      id: "pratos",
      cover: "/projects/produtos/pratos/60 - capa.png",
      title: "Mesa Posta",
      description:
        "Reels de publicidade para linha de pratos, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/pratos/video/60 - video.mp4",
      ],
      images: [],
    },
    {
      id: "lego",
      cover: "/projects/produtos/lego/62 - capa.png",
      title: "Brinquedo de montar",
      description:
        "Reels de publicidade para brinquedo de montar, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/lego/video/62 - video.mp4",
      ],
      images: [],
    },
    {
      id: "pote",
      cover: "/projects/produtos/pote/61 - capa.png",
      title: "Potinhos em stop motion",
      description:
        "Reels de publicidade para potinhos, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/pote/video/61 - video.mp4",
      ],
      images: [],
    },
    {
      id: "taca",
      cover: "/projects/produtos/taca/40 - capa.png",
      title: "Taça de sobremesa",
      description:
        "Reels de publicidade para taça de sobremesa, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/taca/video/40 - video.mp4",
      ],
      images: [],
    },
    {
      id: "mel",
      cover: "/projects/produtos/mel/58 - capa.png",
      title: "Meleira",
      description:
        "Reels de publicidade para meleira, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/produtos/mel/video/58 - video.mp4",
      ],
      images: [],
    },
  ],
  institucional: [
    {
      id: "FMU",
      cover: "/projects/institucional/FMU/capa.png",
      title: "Faculdade FMU",
      description:
        "Projeto feito para a Faculdade FMU, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/FMU/videos/video1.mp4",
      ],
      images: [],
    },

    {
      id: "retro-me",
      cover: "/projects/institucional/retro-me/27 - capa.png",
      title: "Retrospectiva Me digital",
      description: "Reels de retrospectiva para a empresa me digital",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/retro-me/video/27 - video.mp4",
      ],
      images: [],
    },
    {
      id: "trend-me",
      cover: "/projects/institucional/trend-me/1 - capa.png",
      title: "Trend Me digital",
      description: "Reels de trend para agencia me digital",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/trend-me/video/1 - video.mp4",
      ],
      images: [],
    },
    {
      id: "comfort",
      cover: "/projects/institucional/comfort/34 - capa.png",
      title: "Apresentação Comfort Hotel",
      description:
        "Reels de apresentação do Comfort Hotel, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/comfort/video/34 - video.mp4",
      ],
      images: [],
    },
    {
      id: "pascoa-akai",
      cover: "/projects/institucional/pascoa-akai/11 - capa.png",
      title: "Páscoa akai",
      description:
        "Reels temático de páscoa para akai, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/pascoa-akai/video/11 - video.mp4",
      ],
      images: [],
    },
    {
      id: "krill",
      cover: "/projects/institucional/krill/48 - foto.png",
      title: "Rede Krill",
      description:
        "Reels de apresentação da rede Krill, em colaboração com Janaina Hohne",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/krill/video/48 - video.mp4",
      ],
      images: [],
    },
    {
      id: "mulher-me",
      cover: "/projects/institucional/mulher-me/33- capa.png",
      title: "Dia da mulher me digital",
      description: "Reels de dia da mulher para agencia me digital",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/institucional/krill/video/33 - video.mp4",
      ],
      images: [],
    },
  ],
  influencers: [],
  gastronomia: [
    {
      id: "donanice1",
      cover: "/projects/gastronomico/donanice1/50 - capa.png",
      title: "Dona Nice Steakhouse",
      description:
        "Reels de publicidade para Dona Nice Steakhouse, em colaboração com Janaina Hohne",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/donanice1/video/50 - video.mp4",
      ],
      images: [],
    },
    {
      id: "manteigaria1",
      cover: "/projects/gastronomico/manteigaria1/49 - capa.png",
      title: "Manteigaria do porto",
      description:
        "Reels de publicidade para Manteigaria do Porto, em colaboração com Janaina Hohne",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/manteigaria1/video/49 - video.mp4",
      ],
      images: [],
    },
    {
      id: "moqueca",
      cover: "/projects/gastronomico/moqueca/45 - capa.png",
      title: "Moqueca",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/moqueca/video/45 - video.mp4",
      ],
      images: [],
    },
    {
      id: "donanice2",
      cover: "/projects/gastronomico/donanice2/47 - capa.png",
      title: "Dona Nice Steakhouse",
      description:
        "Reels de publicidade para Dona Nice Steakhouse, em colaboração com Janaina Hohne",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/donanice2/video/47 - video.mp4",
      ],
      images: [],
    },
    {
      id: "bemservido",
      cover: "/projects/gastronomico/bemservido/44 - capa.png",
      title: "Pedra Baiana ",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/bemservido/video/44 - video.mp4",
      ],
      images: [],
    },
    {
      id: "carnedesol",
      cover: "/projects/gastronomico/carnedesol/43 - capa.png",
      title: "Carne de Sol",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/carnedesol/video/43 - video.mp4",
      ],
      images: [],
    },
    {
      id: "provolone",
      cover: "/projects/gastronomico/provolone/42 - capa.png",
      title: "Provolone",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/carnedesol/video/42 - video.mp4",
      ],
      images: [],
    },
    {
      id: "strogonof",
      cover: "/projects/gastronomico/strogonof/38 - capa.png",
      title: "Strogonoff",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/strogonof/video/38 - video.mp4",
      ],
      images: [],
    },
    {
      id: "sextasanta",
      cover: "/projects/gastronomico/sextasanta/41- capa.png",
      title: "Sexta feira Santa",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/sextasanta/video/41- video.mp4",
      ],
      images: [],
    },
    {
      id: "mocoto",
      cover: "/projects/gastronomico/mocoto/37 - capa.png",
      title: "Mocotó",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/mocoto/video/37 - video.mp4",
      ],
      images: [],
    },
    {
      id: "piki",
      cover: "/projects/gastronomico/piki/29 - capa.png",
      title: "Piki Burguer",
      description:
        "Reels de publicidade para Piki Burguer, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/piki/video/29 - video.mp4",
      ],
      images: [],
    },
    {
      id: "petiscos",
      cover: "/projects/gastronomico/petiscos/8 - capa.png",
      title: "Petiscos e Porções",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/petiscos/video/8 - video.mp4",
      ],
      images: [],
    },
    {
      id: "camarao",
      cover: "/projects/gastronomico/camarao/7 - capa.png",
      title: "Camarão Recheado",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/camarao/video/7 - video.mp4",
      ],
      images: [],
    },
    {
      id: "carnepais",
      cover: "/projects/gastronomico/carnepais/6 - capa.png",
      title: "Carne para o dia dos pais",
      description:
        "Reels de publicidade de linha de panelas, em colaboração com agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/carnepais/video/6 - video.mp4",
      ],
      images: [],
    },
    {
      id: "escuta",
      cover: "/projects/gastronomico/escuta/5 - capa.png",
      title: "Escuta o cheiro ",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/escuta/video/5 - video.mp4",
      ],
      images: [],
    },
    {
      id: "drink",
      cover: "/projects/gastronomico/drink/4 - capa.png",
      title: "Drinks para happy hour",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/drink/video/4 - video.mp4",
      ],
      images: [],
    },
    {
      id: "lanche",
      cover: "/projects/gastronomico/lanche/3 - capa.png",
      title: "Lanches",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/lanche/video/3 - video.mp4",
      ],
      images: [],
    },
    {
      id: "salada",
      cover: "/projects/gastronomico/salada/2 - capa.png",
      title: "Saladas de verão",
      description:
        "Reels de publicidade para restaurante Pedra Baiana, em colaboraçao com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/gastronomico/salada/video/2 - video.mp4",
      ],
      images: [],
    },
  ],
  ensaios: [
    {
      id: "make",
      cover: "/projects/ensaios/make/capa/1.png",
      title: "Backstage de maquiagem - Ana Costa",
      description: "Cobertura de backstage para ensaio da Ana Costa",
      videos: [],
      images: [
        "/projects/ensaios/make/2.jpg",
        "/projects/ensaios/make/3.jpg",
        "/projects/ensaios/make/4.jpg",
        "/projects/ensaios/make/5.jpg",
        "/projects/ensaios/make/6.jpg",
        "/projects/ensaios/make/7.jpg",
        "/projects/ensaios/make/8.jpg",
        "/projects/ensaios/make/9.jpg",
        "/projects/ensaios/make/10.jpg",
        "/projects/ensaios/make/11.jpg",
        "/projects/ensaios/make/12.jpg",
        "/projects/ensaios/make/13.jpg",
        "/projects/ensaios/make/14.jpg",
        "/projects/ensaios/make/15.jpg",
        "/projects/ensaios/make/16.jpg",
        "/projects/ensaios/make/17.jpg",
        "/projects/ensaios/make/18.jpg",
      ],
    },
    {
      id: "backstage",
      cover: "/projects/ensaios/backstage/capa/64.png",
      title: "Backstage de ensaio - Ana Costa",
      description: "Cobertura de backstage para ensaio da Ana Costa",
      videos: [],
      images: [
        "/projects/ensaios/backstage/1.jpg",
        "/projects/ensaios/backstage/2.jpg",
        "/projects/ensaios/backstage/3.jpg",
        "/projects/ensaios/backstage/4.jpg",
        "/projects/ensaios/backstage/5.jpg",
        "/projects/ensaios/backstage/6.jpg",
        "/projects/ensaios/backstage/7.jpg",
        "/projects/ensaios/backstage/8.jpg",
        "/projects/ensaios/backstage/9.jpg",
        "/projects/ensaios/backstage/10.jpg",
        "/projects/ensaios/backstage/11.jpg",
        "/projects/ensaios/backstage/12.jpg",
        "/projects/ensaios/backstage/13.jpg",
        "/projects/ensaios/backstage/14.jpg",
        "/projects/ensaios/backstage/15.jpg",
        "/projects/ensaios/backstage/16.jpg",
        "/projects/ensaios/backstage/17.jpg",
        "/projects/ensaios/backstage/18.jpg",
        "/projects/ensaios/backstage/19.jpg",
        "/projects/ensaios/backstage/20.jpg",
        "/projects/ensaios/backstage/21.jpg",
        "/projects/ensaios/backstage/22.jpg",
        "/projects/ensaios/backstage/23.jpg",
      ],
    },
    {
      id: "edone",
      cover: "/projects/ensaios/edone/capa/68.png",
      title: "Exposição do artista Edone",
      description: "Cobertura de exposição do artista Edone",
      videos: [],
      images: [
        "/projects/ensaios/edone/1.jpg",
        "/projects/ensaios/edone/2.jpg",
        "/projects/ensaios/edone/3.jpg",
        "/projects/ensaios/edone/4.jpg",
        "/projects/ensaios/edone/5.jpg",
        "/projects/ensaios/edone/6.jpg",
        "/projects/ensaios/edone/7.jpg",
        "/projects/ensaios/edone/8.jpg",
        "/projects/ensaios/edone/9.jpg",
        "/projects/ensaios/edone/10.jpg",
        "/projects/ensaios/edone/11.jpg",
        "/projects/ensaios/edone/12.jpg",
        "/projects/ensaios/edone/13.jpg",
        "/projects/ensaios/edone/14.jpg",
        "/projects/ensaios/edone/15.jpg",
        "/projects/ensaios/edone/16.jpg",
        "/projects/ensaios/edone/17.jpg",
        "/projects/ensaios/edone/18.jpg",
        "/projects/ensaios/edone/19.jpg",
        "/projects/ensaios/edone/20.jpg",
      ],
    },
    {
      id: "sandra",
      cover: "/projects/ensaios/sandra/capa/72.png",
      title: "Ensaio Social - Sandra Mara",
      description: "Ensaio de fotos para redes sociais da advogada Sandra Mara",
      videos: [],
      images: [
        "/projects/ensaios/sandra/1.jpg",
        "/projects/ensaios/sandra/2.jpg",
        "/projects/ensaios/sandra/3.jpg",
        "/projects/ensaios/sandra/4.jpg",
        "/projects/ensaios/sandra/5.jpg",
        "/projects/ensaios/sandra/6.jpg",
        "/projects/ensaios/sandra/7.jpg",
        "/projects/ensaios/sandra/8.jpg",
        "/projects/ensaios/sandra/9.jpg",
        "/projects/ensaios/sandra/10.jpg",
        "/projects/ensaios/sandra/11.jpg",
        "/projects/ensaios/sandra/12.jpg",
        "/projects/ensaios/sandra/13.jpg",
        "/projects/ensaios/sandra/14.jpg",
        "/projects/ensaios/sandra/15.jpg",
        "/projects/ensaios/sandra/16.jpg",
        "/projects/ensaios/sandra/17.jpg",
        "/projects/ensaios/sandra/18.jpg",
        "/projects/ensaios/sandra/19.jpg",
        "/projects/ensaios/sandra/20.jpg",
        "/projects/ensaios/sandra/21.jpg",
        "/projects/ensaios/sandra/22.jpg",
        "/projects/ensaios/sandra/23.jpg",
        "/projects/ensaios/sandra/24.jpg",
        "/projects/ensaios/sandra/25.jpg",
        "/projects/ensaios/sandra/26.jpg",
        "/projects/ensaios/sandra/27.jpg",
        "/projects/ensaios/sandra/28.jpg",
        "/projects/ensaios/sandra/29.jpg",
        "/projects/ensaios/sandra/30.jpg",
        "/projects/ensaios/sandra/31.jpg",
        "/projects/ensaios/sandra/32.jpg",
        "/projects/ensaios/sandra/33.jpg",
        "/projects/ensaios/sandra/34.jpg",
        "/projects/ensaios/sandra/34.jpg",
        "/projects/ensaios/sandra/35.jpg",
        "/projects/ensaios/sandra/36.jpg",
        "/projects/ensaios/sandra/37.jpg",
        "/projects/ensaios/sandra/38.jpg",
        "/projects/ensaios/sandra/39.jpg",
        "/projects/ensaios/sandra/40.jpg",
        "/projects/ensaios/sandra/41.jpg",
        "/projects/ensaios/sandra/42.jpg",
        "/projects/ensaios/sandra/43.jpg",
        "/projects/ensaios/sandra/44.jpg",
        "/projects/ensaios/sandra/45.jpg",
        "/projects/ensaios/sandra/46.jpg",
        "/projects/ensaios/sandra/47.jpg",
        "/projects/ensaios/sandra/48.jpg",
        "/projects/ensaios/sandra/49.jpg",
        "/projects/ensaios/sandra/50.jpg",
        "/projects/ensaios/sandra/51.jpg",
        "/projects/ensaios/sandra/52.jpg",
        "/projects/ensaios/sandra/53.jpg",
        "/projects/ensaios/sandra/54.jpg",
        "/projects/ensaios/sandra/55.jpg",
        "/projects/ensaios/sandra/55.jpg",
        "/projects/ensaios/sandra/56.jpg",
        "/projects/ensaios/sandra/57.jpg",
        "/projects/ensaios/sandra/58.jpg",
        "/projects/ensaios/sandra/59.jpg",
        "/projects/ensaios/sandra/60.jpg",
        "/projects/ensaios/sandra/61.jpg",
        "/projects/ensaios/sandra/62.jpg",
        "/projects/ensaios/sandra/63.jpg",
        "/projects/ensaios/sandra/64.jpg",
        "/projects/ensaios/sandra/65.jpg",
        "/projects/ensaios/sandra/66.jpg",
        "/projects/ensaios/sandra/67.jpg",
        "/projects/ensaios/sandra/68.jpg",
        "/projects/ensaios/sandra/69.jpg",
        "/projects/ensaios/sandra/70.jpg",
        "/projects/ensaios/sandra/71.jpg",
        "/projects/ensaios/sandra/72.jpg",
        "/projects/ensaios/sandra/73.jpg",
        "/projects/ensaios/sandra/74.jpg",
        "/projects/ensaios/sandra/75.jpg",
        "/projects/ensaios/sandra/76.jpg",
        "/projects/ensaios/sandra/77.jpg",
        "/projects/ensaios/sandra/78.jpg",
        "/projects/ensaios/sandra/79.jpg",
        "/projects/ensaios/sandra/80.jpg",
      ],
    },
    {
      id: "circo",
      cover: "/projects/ensaios/circo/capa/70.png",
      title: "Circo Stankowich",
      description: "Cobertura de espetáculo do circo Stankowich",
      videos: [],
      images: [
        "/projects/ensaios/circo/1.jpg",
        "/projects/ensaios/circo/2.jpg",
        "/projects/ensaios/circo/3.jpg",
        "/projects/ensaios/circo/4.jpg",
        "/projects/ensaios/circo/5.jpg",
        "/projects/ensaios/circo/6.jpg",
        "/projects/ensaios/circo/7.jpg",
        "/projects/ensaios/circo/8.jpg",
        "/projects/ensaios/circo/9.jpg",
        "/projects/ensaios/circo/10.jpg",
        "/projects/ensaios/circo/11.jpg",
        "/projects/ensaios/circo/12.jpg",
        "/projects/ensaios/circo/13.jpg",
      ],
    },
    {
      id: "aware",
      cover: "/projects/ensaios/aware/capa/65.png",
      title: "Aware",
      description: "Projeto fotográfico lúdico para universidade",
      videos: [],
      images: [
        "/projects/ensaios/aware/1.jpg",
        "/projects/ensaios/aware/2.jpg",
        "/projects/ensaios/aware/3.jpg",
        "/projects/ensaios/aware/4.jpg",
        "/projects/ensaios/aware/5.jpg",
        "/projects/ensaios/aware/6.jpg",
        "/projects/ensaios/aware/7.jpg",
        "/projects/ensaios/aware/8.jpg",
        "/projects/ensaios/aware/9.jpg",
        "/projects/ensaios/aware/10.jpg",
      ],
    },
    {
      id: "pod",
      cover: "/projects/ensaios/pod/capa/66.png",
      title: "Backstage de Podcast",
      description: "Cobertura de backstage para podcast PodSimplificar",
      videos: [],
      images: [
        "/projects/ensaios/pod/34.jpg",
        "/projects/ensaios/pod/2.jpg",
        "/projects/ensaios/pod/3.jpg",
        "/projects/ensaios/pod/4.jpg",
        "/projects/ensaios/pod/5.jpg",
        "/projects/ensaios/pod/6.jpg",
        "/projects/ensaios/pod/7.jpg",
        "/projects/ensaios/pod/8.jpg",
        "/projects/ensaios/pod/9.jpg",
        "/projects/ensaios/pod/10.jpg",
        "/projects/ensaios/pod/11.jpg",
        "/projects/ensaios/pod/12.jpg",
        "/projects/ensaios/pod/13.jpg",
        "/projects/ensaios/pod/14.jpg",
        "/projects/ensaios/pod/15.jpg",
        "/projects/ensaios/pod/16.jpg",
        "/projects/ensaios/pod/17.jpg",
        "/projects/ensaios/pod/18.jpg",
        "/projects/ensaios/pod/19.jpg",
        "/projects/ensaios/pod/20.jpg",
        "/projects/ensaios/pod/21.jpg",
        "/projects/ensaios/pod/22.jpg",
        "/projects/ensaios/pod/23.jpg",
        "/projects/ensaios/pod/24.jpg",
        "/projects/ensaios/pod/24.jpg",
        "/projects/ensaios/pod/25.jpg",
        "/projects/ensaios/pod/26.jpg",
        "/projects/ensaios/pod/27.jpg",
        "/projects/ensaios/pod/28.jpg",
        "/projects/ensaios/pod/29.jpg",
        "/projects/ensaios/pod/30.jpg",
        "/projects/ensaios/pod/32.jpg",
        "/projects/ensaios/pod/33.jpg",
        "/projects/ensaios/pod/1.jpg",
        ,
      ],
    },
    {
      id: "conceitual",
      cover: "/projects/ensaios/conceitual/capa/73.png",
      title: "Catálogo temático",
      description:
        "Fotos de catálogo temático para redes sociais de linha de acessórios",
      videos: [],
      images: [
        "/projects/ensaios/conceitual/2.jpg",
        "/projects/ensaios/conceitual/3.jpg",
        "/projects/ensaios/conceitual/4.jpg",
        "/projects/ensaios/conceitual/5.jpg",
        "/projects/ensaios/conceitual/6.jpg",
        "/projects/ensaios/conceitual/7.jpg",
        "/projects/ensaios/conceitual/8.jpg",
        "/projects/ensaios/conceitual/9.jpg",
        "/projects/ensaios/conceitual/10.jpg",
        "/projects/ensaios/conceitual/11.jpg",
        "/projects/ensaios/conceitual/12.jpg",
        "/projects/ensaios/conceitual/13.jpg",
        "/projects/ensaios/conceitual/14.jpg",
      ],
    },
    {
      id: "imobiliario",
      cover: "/projects/ensaios/imobiliario/capa/69.png",
      title: "Fotografia imobiliária",
      description: "Fotos para venda de imovel",
      videos: [],
      images: [
        "/projects/ensaios/imobiliario/2.jpg",
        "/projects/ensaios/imobiliario/3.jpg",
        "/projects/ensaios/imobiliario/4.jpg",
        "/projects/ensaios/imobiliario/5.jpg",
        "/projects/ensaios/imobiliario/6.jpg",
        "/projects/ensaios/imobiliario/7.jpg",
        "/projects/ensaios/imobiliario/8.jpg",
        "/projects/ensaios/imobiliario/9.jpg",
        "/projects/ensaios/imobiliario/10.jpg",
        "/projects/ensaios/imobiliario/1.jpg",
      ],
    },
    {
      id: "nail",
      cover: "/projects/ensaios/nail/capa/67.png",
      title: "Nail artist",
      description: "Ensaio para redes sociais da nail artist Carolina Mendes",
      videos: [],
      images: [
        "/projects/ensaios/nail/1.jpg",
        "/projects/ensaios/nail/2.jpg",
        "/projects/ensaios/nail/3.jpg",
        "/projects/ensaios/nail/4.jpg",
        "/projects/ensaios/nail/5.jpg",
        "/projects/ensaios/nail/6.jpg",
        "/projects/ensaios/nail/7.jpg",
        "/projects/ensaios/nail/8.jpg",
        "/projects/ensaios/nail/9.jpg",
        "/projects/ensaios/nail/10.jpg",
        "/projects/ensaios/nail/11.jpg",
        "/projects/ensaios/nail/12.jpg",
        "/projects/ensaios/nail/13.jpg",
        "/projects/ensaios/nail/14.jpg",
        "/projects/ensaios/nail/15.jpg",
        "/projects/ensaios/nail/16.jpg",
        "/projects/ensaios/nail/17.jpg",
        "/projects/ensaios/nail/18.jpg",
        "/projects/ensaios/nail/19.jpg",
        "/projects/ensaios/nail/20.jpg",
        "/projects/ensaios/nail/21.jpg",
        "/projects/ensaios/nail/22.jpg",
        "/projects/ensaios/nail/23.jpg",
        "/projects/ensaios/nail/24.jpg",
        "/projects/ensaios/nail/25.jpg",
        "/projects/ensaios/nail/27.jpg",
        "/projects/ensaios/nail/28.jpg",
        "/projects/ensaios/nail/29.jpg",
        "/projects/ensaios/nail/30.jpg",
        "/projects/ensaios/nail/31.jpg",
        "/projects/ensaios/nail/32.jpg",
        "/projects/ensaios/nail/33.jpg",
        "/projects/ensaios/nail/34.jpg",
        "/projects/ensaios/nail/35.jpg",
        "/projects/ensaios/nail/37.jpg",
        "/projects/ensaios/nail/38.jpg",
        "/projects/ensaios/nail/39.jpg",
        "/projects/ensaios/nail/40.jpg",
        "/projects/ensaios/nail/41.jpg",
        "/projects/ensaios/nail/42.jpg",
        "/projects/ensaios/nail/43.jpg",
        "/projects/ensaios/nail/44.jpg",
        "/projects/ensaios/nail/45.jpg",
        "/projects/ensaios/nail/46.jpg",
        "/projects/ensaios/nail/47.jpg",
      ],
    },
    {
      id: "catalogo",
      cover: "/projects/ensaios/catalogo/capa/74.png",
      title: "Catálogo",
      description: "Fotografia de acessórios para catálogo de lojas virtuais",
      videos: [],
      images: [
        "/projects/ensaios/catalogo/2.jpg",
        "/projects/ensaios/catalogo/3.jpg",
        "/projects/ensaios/catalogo/4.jpg",
        "/projects/ensaios/catalogo/5.jpg",
        "/projects/ensaios/catalogo/6.jpg",
        "/projects/ensaios/catalogo/7.jpg",
        "/projects/ensaios/catalogo/8.jpg",
        "/projects/ensaios/catalogo/9.jpg",
        "/projects/ensaios/catalogo/10.jpg",
        "/projects/ensaios/catalogo/1.jpg",
        "/projects/ensaios/catalogo/11.jpg",
        "/projects/ensaios/catalogo/12.jpg",
        "/projects/ensaios/catalogo/13.jpg",
        "/projects/ensaios/catalogo/14.jpg",
      ],
    },
  ],
  eventos: [
    {
      id: "DJ-TSHOW",
      cover: "/projects/eventos/DJ-TCHOW/10 - cap.png",
      title: "DJ TSHOW",
      description:
        "Apresentação do DJ Tchow, realizado na fetsa Gaia, edição em colaboração com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/eventos/DJ-TCHOW/videos/video.mp4",
      ],
      images: [],
    },
    {
      id: "Circo-Abracadabra",
      cover: "/projects/eventos/Circo-Abracadabra/63 - capa.png",
      title: "Circo  Abracadabra com Dedé Santana",
      description: "Cobertura do espetáculo do circo Abracadabra",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/eventos/Circo-Abracadabra/video/63 - video.mp4",
      ],
      images: [],
    },
    {
      id: "circo-abracadabra-geral",
      cover: "/projects/eventos/circo-abracadabra-geral/53 - capa.png",
      title: "Circo Abracadabra",
      description: "Apresentação do Circo Abracadabra",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/eventos/circo-abracadabra-geral/video/53 - video.mp4",
      ],
      images: [],
    },
    {
      id: "atol",
      cover: "/projects/eventos/atol/13 - capa.png",
      title: "Aniversario Atol",
      description: "Evento de aniversario da Atol",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/eventos/atol/video/13 - video.mp4",
      ],
      images: [],
    },
    {
      id: "serena",
      cover: "/projects/eventos/serena/9 - capa.png",
      title: "Evento Serena",
      description:
        "Cobertura do evento Serena, em colaboração com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/eventos/serena/video/9 - video.mp4",
      ],
      images: [],
    },
    {
      id: "DJ-Festa-gaia",
      cover: "/projects/eventos/Festa-gaia/12 - capa.png",
      title: "Festa Gaia",
      description:
        "Edição de aftermovie da festa Gaia, em colaboração com a agencia de publicidade",
      videos: [
        "https://public-tv-productions.s3.sa-east-1.amazonaws.com/projects/eventos/festa-gaia/videos/12 - video.mp4",
      ],
      images: [],
    },
  ],
};
